version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "00:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 10
    groups:
      nextjs:
        patterns:
          - next
          - eslint-config-next
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
